version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/app
      - ./reports:/app/reports
    environment:
      - PYTHONPATH=/app
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY:-dummy_key}
      - NOTE_SESSION_TOKEN=${NOTE_SESSION_TOKEN:-dummy_token}
      - NOTE_CSRF_TOKEN=${NOTE_CSRF_TOKEN:-dummy_token}
    command: bash
  
  test:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/app
      - ./reports:/app/reports
    environment:
      - PYTHONPATH=/app
      - OPENROUTER_API_KEY=dummy_key_for_tests
      - NOTE_SESSION_TOKEN=dummy_token_for_tests
      - NOTE_CSRF_TOKEN=dummy_token_for_tests
    command: test
  
  test-unit:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/app
      - ./reports:/app/reports
    environment:
      - PYTHONPATH=/app
      - OPENROUTER_API_KEY=dummy_key_for_tests
      - NOTE_SESSION_TOKEN=dummy_token_for_tests
      - NOTE_CSRF_TOKEN=dummy_token_for_tests
    command: test tests/unit
  
  test-integration:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/app
      - ./reports:/app/reports
    environment:
      - PYTHONPATH=/app
      - OPENROUTER_API_KEY=dummy_key_for_tests
      - NOTE_SESSION_TOKEN=dummy_token_for_tests
      - NOTE_CSRF_TOKEN=dummy_token_for_tests
    command: test tests/integration
  
  test-coverage:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/app
      - ./reports:/app/reports
    environment:
      - PYTHONPATH=/app
      - OPENROUTER_API_KEY=dummy_key_for_tests
      - NOTE_SESSION_TOKEN=dummy_token_for_tests
      - NOTE_CSRF_TOKEN=dummy_token_for_tests
    command: test coverage 