name: Convert Dev Diary to Zenn Article

on:
  push:
    branches:
      - main
    paths:
      - 'dev-records/**.md'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  diary-converter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2  # コミット履歴を2件取得（変更ファイル検出のため）

      - name: Setup environment
        run: |
          # スクリプトに実行権限を付与
          chmod +x ./tools/diary-filename-processor.sh
          chmod +x ./tools/find-latest-diary.sh
          chmod +x ./tools/find-prev-article.sh
          chmod +x ./tools/replace_template_placeholders.sh
          chmod +x ./tools/document_processor.py

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x' # 最新のPython 3系を使用

      - name: Install Content-Converter
        run: |
          pip install -r https://raw.githubusercontent.com/centervil/Content-Converter/refs/heads/main/requirements.txt

      - name: Find latest updated diary file
        id: find-diary
        run: |
          eval $(./tools/find-latest-diary.sh)
          echo "diary_file=${diary_file}" >> $GITHUB_OUTPUT
          echo "output_file=${output_file}" >> $GITHUB_OUTPUT
          echo "LATEST_DIARY=${diary_file}" >> $GITHUB_ENV

      - name: Find previous article slug
        id: find-prev-article
        run: |
          eval $(./tools/find-prev-article.sh)
          echo "prev_article_slug=${prev_article_slug}" >> $GITHUB_OUTPUT

      - name: Replace placeholders in Zenn template
        run: |
          ./tools/replace_template_placeholders.sh "${{ secrets.LLM_MODEL }}" "${{ steps.find-prev-article.outputs.prev_article_slug }}" templates/zenn_template.md templates/zenn_template_filled.md

      - name: Run Content-Converter
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          LLM_MODEL: ${{ secrets.LLM_MODEL }}
        run: |
          python -m content_converter.cli --input "${{ steps.find-diary.outputs.diary_file }}" --output "${{ steps.find-diary.outputs.output_file }}" --template templates/zenn_template_filled.md --prompt prompts/zenn_article_prompt.txt

      - name: Post-process generated article
        run: |
          python ./tools/document_processor.py "${{ steps.find-diary.outputs.output_file }}"

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add articles/
          git commit -m "Add new Zenn article from ${{ env.LATEST_DIARY }}"
          git push origin main
