name: Convert Dev Diary to Zenn Article

on:
  push:
    branches:
      - main
    paths:
      - 'dev-records/**.md'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  diary-converter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2  # コミット履歴を2件取得（変更ファイル検出のため）

      - name: Setup environment
        run: |
          # スクリプトに実行権限を付与
          chmod +x ./tools/diary-filename-processor.sh

      - name: Find latest updated diary file
        id: find-diary
        run: |
          # 最新の開発日記ファイルを検出
          LATEST_DIARY=$(find dev-records -type f -name "*.md" | sort -r | head -n 1)
          
          echo "LATEST_DIARY: $LATEST_DIARY" 
          
          # Zenn用のファイル名を生成
          OUTPUT_FILENAME=$(./tools/diary-filename-processor.sh "$LATEST_DIARY")
          
          echo "OUTPUT_FILENAME: $OUTPUT_FILENAME"
          
          # articlesディレクトリの存在確認
          mkdir -p articles
          
          echo "diary_file=$LATEST_DIARY" >> $GITHUB_OUTPUT
          echo "output_file=articles/$OUTPUT_FILENAME" >> $GITHUB_OUTPUT
          echo "LATEST_DIARY=$LATEST_DIARY" >> $GITHUB_ENV

      - name: Find previous article slug
        id: find-prev-article
        run: |
          # 前回の記事スラッグを検出
          LATEST_ARTICLE=$(find articles -type f -name "*.md" | sort -r | head -n 1)
          if [ -n "$LATEST_ARTICLE" ]; then
            PREV_ARTICLE_SLUG=$(basename "$LATEST_ARTICLE" .md)
            echo "PREV_ARTICLE_SLUG: $PREV_ARTICLE_SLUG"
            echo "prev_article_slug=$PREV_ARTICLE_SLUG" >> $GITHUB_OUTPUT
          else
            echo "前回の記事が見つかりません"
            echo "prev_article_slug=" >> $GITHUB_OUTPUT
          fi

      - name: Run diary-converter
        uses: centervil/Diary-Converter@main
        with:
          source_file: ${{ steps.find-diary.outputs.diary_file }}
          destination_file: ${{ steps.find-diary.outputs.output_file }}
          api_key: ${{ secrets.GOOGLE_API_KEY }}
          model: gemini-2.5-pro-exp-03-25
          debug: 'true'
          prev_article: ${{ steps.find-prev-article.outputs.prev_article_slug }}
          template: templates/zenn_template.md

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add articles/
          git commit -m "Add new Zenn article from ${{ env.LATEST_DIARY }}"
          git push origin main
